### ISSUE TITLE
Is there support for mocking the Lims?

### ISSUE THREAD

**Issue by gaviriar** [crukci-bioinformatics/clarityclient#7]
Hi @rich7409, Quick question, does this library support enabling serving mock data from the LIMS or mocking the Clarity server itself such that integration tests could be done?

I am facing a situation where I may not have access to the LIMS when performing testing, and therefore would like to mock the interactions with the LIMS server. How would you normally deal with this kind of situation?

**Comment by rich7409** [comment]
Hi. There are means to do that but it's not in the public library on GitHub. For reproducible tests I've recorded the calls and responses to and from a real Clarity server and saved those responses so that a unit test can repeat the calls without a real server behind it.

It is a bit fiddly and as I say that code hasn't been released as it's part of the site specific library we have that builds on the general client. I've done this with two aspects. The playback one goes around the calls on the RestTemplate to intercept the getForObject and getForEntity calls. The recording one goes around the API implementation itself and just writes any reply from retrieve, load and loadAll to a file for the entity or entities returned.

**Comment by gaviriar** [comment]
Hi @rich7409, thanks for the reply. That's an interesting approach, I had not thought of doing it that way i.e. recording the calls. did you manually write the code to record the calls and responses?

This got me/us thinking that we would rather use a tool to help us mock the LIMS, we have settled for testing recording with http://wiremock.org/ I will let you know how we get on with this.

**Comment by rich7409** [comment]
Yes, the reading and writing of the messages I wrote. Attached are those files. The recording ones write the XML replies from the server to a file called &lt;class&gt;-&lt;lims id&gt;.xml in a directory. The "PrerecordedServerAspect" gets in front of the RestTemplate class and creates objects from the previously recorded XML files rather than going to the server.
[recording_and_playback.tar.gz](https://github.com/crukci-bioinformatics/clarityclient/files/2446198/recording_and_playback.tar.gz)

**Comment by gaviriar** [comment]
@rich7409, thank you for sharing. Will check it out and get back to you. :+1:
